package main.java.com.seo.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import main.java.com.seo.auto.utils.UtilsMeth;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

public class KeyGen {
    private JPanel keyGenPanel;
    private JLabel keyGenLbl;
    private JTextField computerIdTxt;
    private JLabel genLbl;
    private JTextField generatedTxt;
    private JButton genBtn;

    public KeyGen() {
        genBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                generatedTxt.setText(UtilsMeth.encrypt(computerIdTxt.getText()));
            }
        });
    }

    public JPanel getKeyGenPanel() {
        return keyGenPanel;
    }

    public void setKeyGenPanel(JPanel keyGenPanel) {
        this.keyGenPanel = keyGenPanel;
    }

    public static void main(String[] args) throws IOException {
        JFrame frame = new JFrame("KeyGen");

        frame.setContentPane(new KeyGen().getKeyGenPanel());
        frame.setMinimumSize(new Dimension(500, 150));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        keyGenPanel = new JPanel();
        keyGenPanel.setLayout(new GridLayoutManager(3, 2, new Insets(10, 10, 10, 10), -1, -1));
        keyGenLbl = new JLabel();
        keyGenLbl.setText("Computer Id");
        keyGenPanel.add(keyGenLbl, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        computerIdTxt = new JTextField();
        keyGenPanel.add(computerIdTxt, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        genLbl = new JLabel();
        genLbl.setText("Generated Key");
        keyGenPanel.add(genLbl, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generatedTxt = new JTextField();
        generatedTxt.setEditable(false);
        keyGenPanel.add(generatedTxt, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        genBtn = new JButton();
        genBtn.setText("Generate Key");
        keyGenPanel.add(genBtn, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return keyGenPanel;
    }

}
